Sprint 04
DDENNEDD/MovieQuiz-ios pull request #2
Opened 2022-11-22 21:13 UTC by DDENNEDD

Д/З по спринту 4

2022-11-23 14:55 UTC, mmbabaev requested changes

2022-11-23 14:55 UTC, mmbabaev commented on .idea/.gitignore
> +# Default ignored files
рекомендую пользоваться gitignore, чтобы не попадали эти файлы

2022-11-23 14:55 UTC, mmbabaev commented on MovieQuiz/AppDelegate.swift
> +        //sleep(3)
можно удалить

2022-11-23 14:55 UTC, mmbabaev commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
>  <?xml version="1.0" encoding="UTF-8"?>
У корневой StackView не хватает bottom constraint до safe area (проверить верстку на iPhone 14 plus).  
<img width="704" alt="Screen Shot 2022-11-21 at 16 48 27" src="https://user-images.githubusercontent.com/12600807/203071237-b3174e10-fa68-4c9e-b8c2-be67958027c6.png">


После этого проверьте верстку на iPhone 13 mini. Скорее всего нужно будет поправить верхний и нижний констрейнты лейбла вопроса на 0

<img width="495" alt="Screen Shot 2022-11-21 at 16 47 52" src="https://user-images.githubusercontent.com/12600807/203071104-244cba10-6e46-4f9c-b86d-9bb2a4aa83ed.png">

2022-11-23 14:55 UTC, mmbabaev commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> -<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="20037" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
Цвет фона должен быть `YP Black` из макетов

2022-11-23 14:55 UTC, mmbabaev commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="21507" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
Кнопки не должны быть написаны капсом

2022-11-23 14:55 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
Необязательно: если быстро нажимать одну и ту же кнопку, то срабатывают лишние нажатия, пока мы ожидаем следующего вопроса. Чтобы этого не было, можно использовать свойство isEnabled. При начале ожидания "выключать" кнопку, после ожидания "включать" https://developer.apple.com/documentation/uikit/uicontrol/1618217-isenabled

2022-11-23 15:21 UTC, mmbabaev approved these changes

2022-11-23 21:30 UTC, DDENNEDD commented on .idea/.gitignore
> +# Default ignored files
попытался, не знаю получилось или нет

2022-11-23 21:30 UTC, DDENNEDD commented on MovieQuiz/AppDelegate.swift
> +        //sleep(3)
удалил

2022-11-23 21:31 UTC, DDENNEDD commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
>  <?xml version="1.0" encoding="UTF-8"?>
исправил, SE и Plus - норм

2022-11-23 21:31 UTC, DDENNEDD commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
>  <?xml version="1.0" encoding="UTF-8"?>
mini и Plus

2022-11-23 21:31 UTC, DDENNEDD commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> -<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="20037" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
исправил

2022-11-23 21:31 UTC, DDENNEDD commented on MovieQuiz/Presentation/Base.lproj/Main.storyboard
> +<document type="com.apple.InterfaceBuilder3.CocoaTouch.Storyboard.XIB" version="3.0" toolsVersion="21507" targetRuntime="iOS.CocoaTouch" propertyAccessControl="none" useAutolayout="YES" useTraitColle
исправил

2022-11-23 21:32 UTC, DDENNEDD commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 1.0) {
добавил функционал блокировки до показа след. вопроса

2022-11-24 09:25 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction private func yesButtonClicked(_ sender: UIButton) {
порядок в viewController обычно делают такой: 

1. Properties
2. override funcs
3. IBAction funcs
4. other funcs  другие типы - сверху или снизу

2022-11-24 09:25 UTC, mmbabaev approved these changes

2022-11-24 14:02 UTC, DDENNEDD commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBAction private func yesButtonClicked(_ sender: UIButton) {
принято, спасибо

2022-11-24 14:02 UTC, merged